[package]
name = "gelixrs"
version = "0.1.0"
authors = ["Felix Ang. <felix.ang@protonmail.com>"]
edition = "2018"

[dependencies]
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "llvm7-0" }
structopt = "0.2.18"
lazy_static = "1.3.0"